# Railway Configuration File
# Reference: https://docs.railway.com/reference/config-as-code

[build]
# Builder to use (RAILPACK, DOCKERFILE, or NIXPACKS)
builder = "RAILPACK"

# Build command to run
buildCommand = "python -m pip install -r requirements.txt && python unzip_files.py && rm -f data/*.zip"

# Watch patterns for conditional deploys (optional)
# watchPatterns = ["**"]

[deploy]
# Start command to run the application with uvicorn
# Railway provides $PORT environment variable dynamically
startCommand = "python -m uvicorn api.main:app --host 0.0.0.0 --port ${PORT:-8000}"

# Environment variables for Railpack to install system packages
# https://railpack.com/guides/installing-packages
[deploy.environmentVariables]
# Install SQLite3 library at runtime (needed by Python's sqlite3 module)
RAILPACK_DEPLOY_APT_PACKAGES = "libsqlite3-0"

# Restart policy when deployment crashes
restartPolicyType = "ON_FAILURE"

# Maximum number of retries for restart policy
restartPolicyMaxRetries = 5

# Runtime version
runtime = "V2"

# Number of replicas
numReplicas = 1

# Memory limit override
limitOverride = {"containers":{"memoryBytes":4000000000}}

# Sleep application when inactive
sleepApplication = true

# Use legacy stacker
useLegacyStacker = false

# Multi-region configuration
multiRegionConfig = {"europe-west4-drams3a":{"numReplicas":1}}

# Deployment lifecycle settings
# overlapSeconds = 60  # Time new and old deploys overlap
# drainingSeconds = 10  # Time between SIGTERM and SIGKILL